version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./static:/app/static
    links:
      - php-fpm
    depends_on:
      - php

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=docker # for cli???
      XDEBUG_CONFIG: client_host=host.docker.internal
      XDEBUG_MODE: debug
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/app
    links:
      - mysql
      - memcached
      - rabbitmq

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: Users
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
