version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/app
    links:
      - mysql
      - memcached
      - rabbitmq

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: Users
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:latest




