version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./:/var/www/app
    links:
      - php-fpm
    depends_on:
      - php

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/app
      - /var/www/docker-study.loc/recipe-09/php:/var/www/app
      - /var/www/docker-study.loc/recipe-09/docker/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql
      - memcached
      - rabbitmq

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: Users
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:latest




